"""initial migration

Revision ID: 1eb2146609be
Revises: 
Create Date: 2026-03-25 15:25:06.109284
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1eb2146609be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('organization_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repository_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repository_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('all_service_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('service_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_tasks'))
    )
    op.create_index(op.f('ix_ai_tasks_id'), 'ai_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_ai_tasks_task_id'), 'ai_tasks', ['task_id'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_repositories_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories'))
    )
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_table('user_projects',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_user_projects_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_projects_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'project_id', name=op.f('pk_user_projects'))
    )
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_services_repository_id_repositories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_table('apis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('request_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_apis_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apis'))
    )
    op.create_index(op.f('ix_apis_id'), 'apis', ['id'], unique=False)
    op.create_table('api_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Uuid(), nullable=False),
    sa.Column('service_from_id', sa.Uuid(), nullable=False),
    sa.Column('service_to_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['apis.id'], name=op.f('fk_api_calls_api_id_apis')),
    sa.ForeignKeyConstraint(['service_from_id'], ['services.id'], name=op.f('fk_api_calls_service_from_id_services')),
    sa.ForeignKeyConstraint(['service_to_id'], ['services.id'], name=op.f('fk_api_calls_service_to_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_calls'))
    )
    op.create_index(op.f('ix_api_calls_id'), 'api_calls', ['id'], unique=False)
    op.create_table('api_changes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('commit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('change_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('change_degree', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['apis.id'], name=op.f('fk_api_changes_api_id_apis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_changes'))
    )
    op.create_index(op.f('ix_api_changes_id'), 'api_changes', ['id'], unique=False)
    op.create_table('impact_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_change_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['api_change_id'], ['api_changes.id'], name=op.f('fk_impact_analyses_api_change_id_api_changes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_analyses'))
    )
    op.create_index(op.f('ix_impact_analyses_id'), 'impact_analyses', ['id'], unique=False)
    op.create_table('impact_analysis_services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('impact_analysis_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['impact_analysis_id'], ['impact_analyses.id'], name=op.f('fk_impact_analysis_services_impact_analysis_id_impact_analyses')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_impact_analysis_services_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_analysis_services'))
    )
    op.create_index(op.f('ix_impact_analysis_services_id'), 'impact_analysis_services', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('impact_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('api_change_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['api_change_id'], ['api_changes.id'], name=op.f('fk_notifications_api_change_id_api_changes')),
    sa.ForeignKeyConstraint(['impact_analysis_id'], ['impact_analyses.id'], name=op.f('fk_notifications_impact_analysis_id_impact_analyses')),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_impact_analysis_services_id'), table_name='impact_analysis_services')
    op.drop_table('impact_analysis_services')
    op.drop_index(op.f('ix_impact_analyses_id'), table_name='impact_analyses')
    op.drop_table('impact_analyses')
    op.drop_index(op.f('ix_api_changes_id'), table_name='api_changes')
    op.drop_table('api_changes')
    op.drop_index(op.f('ix_api_calls_id'), table_name='api_calls')
    op.drop_table('api_calls')
    op.drop_index(op.f('ix_apis_id'), table_name='apis')
    op.drop_table('apis')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_table('user_projects')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_ai_tasks_task_id'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_id'), table_name='ai_tasks')
    op.drop_table('ai_tasks')
    # ### end Alembic commands ###
