"""added projects,fix_records tables, added project_id column. deleted impact_analysis, impact_analysis_service

Revision ID: 3a990da5dfa4
Revises: b2d8f4c1a9e7
Create Date: 2026-06-24 10:37:33.830304
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a990da5dfa4'
down_revision: Union[str, None] = 'b2d8f4c1a9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('fix_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pr_id', sa.Uuid(), nullable=False),
    sa.Column('downstream_service_id', sa.Uuid(), nullable=False),
    sa.Column('validation_status', sa.Enum('Passed', 'FailedRetryable', 'FailedExhausted', name='validationstatus'), nullable=False),
    sa.Column('validation_decision', sa.Enum('Valid', 'Retry', 'ManualReview', name='validationdecision'), nullable=False),
    sa.Column('schema_validation_passed', sa.Boolean(), nullable=True),
    sa.Column('schema_validation_errors', sa.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('static_analysis_passed', sa.Boolean(), nullable=True),
    sa.Column('static_analysis_errors', sa.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('syntax_check_passed', sa.Boolean(), nullable=True),
    sa.Column('syntax_check_errors', sa.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('generated_patch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('formatted_patch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('patch_explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semantic_validation_ran', sa.Boolean(), nullable=False),
    sa.Column('semantic_validation_passed', sa.Boolean(), nullable=True),
    sa.Column('semantic_validation_notes', sa.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('semantic_validation_score', sa.Float(), nullable=True),
    sa.Column('branch_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('final_outcome', sa.Enum('Completed', 'ManualReviewRequired', name='finaloutcome'), nullable=True),
    sa.ForeignKeyConstraint(['downstream_service_id'], ['services.id'], name=op.f('fk_fix_records_downstream_service_id_services')),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_requests.id'], name=op.f('fk_fix_records_pr_id_pull_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fix_records'))
    )
    op.create_index(op.f('ix_fix_records_id'), 'fix_records', ['id'], unique=False)
    op.drop_index(op.f('ix_impact_analysis_services_id'), table_name='impact_analysis_services')
    op.drop_table('impact_analysis_services')
    op.drop_index(op.f('ix_impact_analysis_id'), table_name='impact_analysis')
    op.drop_table('impact_analysis')
    op.alter_column('api_changes', 'pr_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('api_changes', 'method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('api_changes', 'endpoint_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('api_changes', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('api_changes', 'line_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('repositories', sa.Column('project_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_repositories_project_id_projects'), 'repositories', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_repositories_project_id_projects'), 'repositories', type_='foreignkey')
    op.drop_column('repositories', 'project_id')
    op.alter_column('api_changes', 'line_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('api_changes', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('api_changes', 'endpoint_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('api_changes', 'method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('api_changes', 'pr_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('impact_analysis_services',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('impact_analysis_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['impact_analysis_id'], ['impact_analysis.id'], name=op.f('fk_impact_analysis_services_impact_analysis_id_impact_analysis')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_impact_analysis_services_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_analysis_services'))
    )
    op.create_index(op.f('ix_impact_analysis_services_id'), 'impact_analysis_services', ['id'], unique=False)
    op.create_table('impact_analysis',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('api_change_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['api_change_id'], ['api_changes.id'], name=op.f('fk_impact_analysis_api_change_id_api_changes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_analysis'))
    )
    op.create_index(op.f('ix_impact_analysis_id'), 'impact_analysis', ['id'], unique=False)
    op.drop_index(op.f('ix_fix_records_id'), table_name='fix_records')
    op.drop_table('fix_records')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
