"""added new tables

Revision ID: ec15c3544f17
Revises: d3e0e3d8fadd
Create Date: 2026-06-25 17:27:05.567558
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec15c3544f17'
down_revision: Union[str, None] = 'd3e0e3d8fadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_analysis_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('callback_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('failed_tasks', sa.Integer(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('callback_delivery_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('callback_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependency_analysis_runs'))
    )
    op.create_index(op.f('ix_dependency_analysis_runs_analysis_run_id'), 'dependency_analysis_runs', ['analysis_run_id'], unique=True)
    op.create_index(op.f('ix_dependency_analysis_runs_id'), 'dependency_analysis_runs', ['id'], unique=False)
    op.create_index(op.f('ix_dependency_analysis_runs_project_id'), 'dependency_analysis_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_dependency_analysis_runs_status'), 'dependency_analysis_runs', ['status'], unique=False)
    op.create_table('dependency_analysis_task_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('repository_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependency_analysis_task_links'))
    )
    op.create_index(op.f('ix_dependency_analysis_task_links_analysis_run_id'), 'dependency_analysis_task_links', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_dependency_analysis_task_links_id'), 'dependency_analysis_task_links', ['id'], unique=False)
    op.create_index(op.f('ix_dependency_analysis_task_links_task_id'), 'dependency_analysis_task_links', ['task_id'], unique=True)
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs', if_exists=True)
    op.drop_table('checkpoint_blobs', if_exists=True)
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints', if_exists=True)
    op.drop_table('checkpoints', if_exists=True)
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes', if_exists=True)
    op.drop_table('checkpoint_writes', if_exists=True)
    op.drop_table('checkpoint_migrations', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.drop_index(op.f('ix_dependency_analysis_task_links_task_id'), table_name='dependency_analysis_task_links')
    op.drop_index(op.f('ix_dependency_analysis_task_links_id'), table_name='dependency_analysis_task_links')
    op.drop_index(op.f('ix_dependency_analysis_task_links_analysis_run_id'), table_name='dependency_analysis_task_links')
    op.drop_table('dependency_analysis_task_links')
    op.drop_index(op.f('ix_dependency_analysis_runs_status'), table_name='dependency_analysis_runs')
    op.drop_index(op.f('ix_dependency_analysis_runs_project_id'), table_name='dependency_analysis_runs')
    op.drop_index(op.f('ix_dependency_analysis_runs_id'), table_name='dependency_analysis_runs')
    op.drop_index(op.f('ix_dependency_analysis_runs_analysis_run_id'), table_name='dependency_analysis_runs')
    op.drop_table('dependency_analysis_runs')
    # ### end Alembic commands ###
