"""some modifications

Revision ID: f35a069691ee
Revises: 6932e99173ae
Create Date: 2026-07-01 14:49:39.221966
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f35a069691ee'
down_revision: Union[str, None] = '6932e99173ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_repositories',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('repository_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_project_repositories_repository_id_repositories')),
    sa.PrimaryKeyConstraint('project_id', 'repository_id', name=op.f('pk_project_repositories'))
    )
    op.add_column('api_call_changes', sa.Column('analysis_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_api_call_changes_analysis_id'), 'api_call_changes', ['analysis_id'], unique=False)
    op.add_column('api_changes', sa.Column('analysis_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_api_changes_analysis_id'), 'api_changes', ['analysis_id'], unique=False)
    op.add_column('dependency_analysis_runs', sa.Column('analysis_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_dependency_analysis_runs_analysis_run_id'), table_name='dependency_analysis_runs')
    op.create_index(op.f('ix_dependency_analysis_runs_analysis_id'), 'dependency_analysis_runs', ['analysis_id'], unique=True)
    op.drop_column('dependency_analysis_runs', 'analysis_run_id')
    op.add_column('dependency_analysis_task_links', sa.Column('analysis_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_dependency_analysis_task_links_analysis_run_id'), table_name='dependency_analysis_task_links')
    op.create_index(op.f('ix_dependency_analysis_task_links_analysis_id'), 'dependency_analysis_task_links', ['analysis_id'], unique=False)
    op.drop_column('dependency_analysis_task_links', 'analysis_run_id')
    op.add_column('fix_records', sa.Column('project_id', sa.Uuid(), nullable=True))
    op.add_column('fix_records', sa.Column('analysis_id', sa.Uuid(), nullable=True))
    op.add_column('fix_records', sa.Column('fix_id', sa.Uuid(), nullable=False))
    op.add_column('fix_records', sa.Column('downstream_service_ids', postgresql.ARRAY(sa.UUID()), nullable=True))
    op.alter_column('fix_records', 'pr_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_fix_records_analysis_id'), 'fix_records', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_fix_records_fix_id'), 'fix_records', ['fix_id'], unique=False)
    op.create_index(op.f('ix_fix_records_project_id'), 'fix_records', ['project_id'], unique=False)
    op.drop_column('fix_records', 'downstream_services_ids')
    op.drop_column('fix_records', 'run_id')
    op.drop_column('repositories', 'project_id')
    op.add_column('service_changes', sa.Column('analysis_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_service_changes_analysis_id'), 'service_changes', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_changes_analysis_id'), table_name='service_changes')
    op.drop_column('service_changes', 'analysis_id')
    op.add_column('repositories', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('fix_records', sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('fix_records', sa.Column('downstream_services_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_fix_records_project_id'), table_name='fix_records')
    op.drop_index(op.f('ix_fix_records_fix_id'), table_name='fix_records')
    op.drop_index(op.f('ix_fix_records_analysis_id'), table_name='fix_records')
    op.alter_column('fix_records', 'pr_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('fix_records', 'downstream_service_ids')
    op.drop_column('fix_records', 'fix_id')
    op.drop_column('fix_records', 'analysis_id')
    op.drop_column('fix_records', 'project_id')
    op.add_column('dependency_analysis_task_links', sa.Column('analysis_run_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_dependency_analysis_task_links_analysis_id'), table_name='dependency_analysis_task_links')
    op.create_index(op.f('ix_dependency_analysis_task_links_analysis_run_id'), 'dependency_analysis_task_links', ['analysis_run_id'], unique=False)
    op.drop_column('dependency_analysis_task_links', 'analysis_id')
    op.add_column('dependency_analysis_runs', sa.Column('analysis_run_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_dependency_analysis_runs_analysis_id'), table_name='dependency_analysis_runs')
    op.create_index(op.f('ix_dependency_analysis_runs_analysis_run_id'), 'dependency_analysis_runs', ['analysis_run_id'], unique=True)
    op.drop_column('dependency_analysis_runs', 'analysis_id')
    op.drop_index(op.f('ix_api_changes_analysis_id'), table_name='api_changes')
    op.drop_column('api_changes', 'analysis_id')
    op.drop_index(op.f('ix_api_call_changes_analysis_id'), table_name='api_call_changes')
    op.drop_column('api_call_changes', 'analysis_id')
    op.drop_table('project_repositories')
    # ### end Alembic commands ###
